name: Code Analysis

on:
  push:
    branches:
      - 'feature/*'

jobs:      
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Pylint
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install pylint
        pylint src/ --rcfile=.pylintrc
      
  pyflakes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Pyflakes
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install pyflakes
        pyflakes src/

  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Markdownlint
      run: |
        npm install markdownlint-cli
        markdownlint "**/*.md"