name: Code Analysis

on: [push]

jobs:      
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Pylint
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install pylint
        pylint src/ --rcfile=.pylintrc
      
  pyflakes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Pyflakes
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install pyflakes
        pyflakes src/

  check-next-tag:
    runs-on: ubuntu-latest
    needs: [pylint, pyflakes]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get latest tag
        id: get_latest_tag
        run: |
          tag_count=$(git tag | wc -l)
          if [[ $tag_count -eq 0 ]]; then
            latest_tag="1.0.0"
          else
            latest_tag=$(git describe --tags --abbrev=0 2>&1)
            if [[ "$latest_tag" == "fatal: No se encontraron nombres, no se puede describir nada." ]]; then
              latest_tag="1.0.0"
            fi
          fi
          echo "::set-output name=latest_tag::$latest_tag"
      
      - name: Generate next tag
        id: generate_next_tag
        if: ${{ steps.get_latest_tag.outputs.latest_tag != '1.0.0' }}
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          next_tag=$(echo $latest_tag | awk -F. 'BEGIN{OFS="."}{$NF++;print}')
          echo "::set-output name=next_tag::$next_tag"
      
      - name: Set default tag
        if: ${{ steps.get_latest_tag.outputs.latest_tag == '1.0.0' }}
        run: |
          echo "::set-output name=next_tag::1.0.0"
      
      - name: Print next tag
        run: |
          next_tag=${{ steps.generate_next_tag.outputs.next_tag }}
          if [[ -z "$next_tag" ]]; then
            echo "Next tag is 1.0.0"
          else
            echo "Next tag is $next_tag"
          fi


