name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Xavier Martinez"
          git config --global user.email "xavimartinezfa@gmail.com"

      - name: Install dependencies
        run: |
          pip install setuptools_scm
          pip install commitizen
          pip install bump2version

      - name: Get the latest version
        id: get-version
        run: echo "::set-output name=version::$(python -c 'import src.setup; print(src.setup.__version__)')"

      - name: Bump version if needed
        id: bump-version
        if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[chore]')
        run: |
          cz bump --changelog -y && git push origin main

      - name: Build distribution package
        run: python src/setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
